NameError: name 'MEDIA_TYPE_CHANNEL' is not defined
# These MEDIA_TYPE_* constants are deprecated as of Home Assistant 2022.10.
# Please use the MediaType enum instead.

fixed missing changes